spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/signalwealth_user_service
    username: ronald
    password: password
    driverClassName: org.postgresql.Driver
